name: SMS Sender

on:
  push:
    branches: [ 'main' ]  # Runs on pushes to any branch
  pull_request:
    branches: [ 'main' ]  # Runs on pull requests to any branch
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes for testing

permissions:
  contents: read  # Only read permissions needed

jobs:
  run_py_file:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - uses: actions/checkout@v4
    
    # Step 2: Set up Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Step 3: Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pushbullet.py
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    # Step 4: Run the Python script to send SMS notifications
    - name: Run Python script
      env:
        PUSHBULLET_API_KEY: ${{ secrets.PUSHBULLET_API_KEY }}  # Load the secret key from GitHub Secrets
      run: python sai.py  # Ensure this script is in the root directory
